# Generated by Django 4.1.4 on 2022-12-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='AdProject',
        ),
        migrations.RenameModel(
            old_name='Formats',
            new_name='Format',
        ),
    ]
