# Generated by Django 4.1.4 on 2023-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_type',
            field=models.IntegerField(choices=[(1, 'HTTP'), (2, 'SOCKS3')], default=1),
        ),
    ]
