# Generated by Django 4.1.4 on 2023-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_proxy_description_proxy_enabled_proxy_proxy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
